[project]
name = "pyscanner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imutils>=0.5.4",
    "opencv-python>=4.13.0.92",
    "scikit-image>=0.26.0",
]
